add new action to validate mix is bumped up before mering (#33)

diff --git a/.github/workflows/elixir.yaml b/.github/workflows/elixir.yaml
--- a/.github/workflows/elixir.yaml
+++ b/.github/workflows/elixir.yaml
@@ -124,3 +124,37 @@ jobs:
       # Step: Check for unused dependencies in the project
       - name: Check unused dependencies
         run: mix deps.unlock --check-unused
+
+  version_check:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Checkout PR branch
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+
+      - name: Get version in PR branch
+        id: pr_version
+        run: |
+          VERSION=$(grep -m 1 '@version' mix.exs | sed 's/.*"\([0-9.]*\)".*/\1/')
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Fetch main branch
+        run: git fetch origin main:refs/remotes/origin/main
+
+      - name: Get version in main branch
+        id: main_version
+        run: |
+          MAIN_VERSION=$(git show origin/main:mix.exs | grep -m 1 '@version' | sed 's/.*"\([0-9.]*\)".*/\1/')
+          echo "MAIN_VERSION=$MAIN_VERSION" >> $GITHUB_ENV
+
+      - name: Fail if version not bumped
+        run: |
+          echo "PR version: $VERSION"
+          echo "Main version: $MAIN_VERSION"
+          if [ "$VERSION" = "$MAIN_VERSION" ]; then
+            echo "Error: Version in mix.exs was not bumped. Please increment @version before merging to main."
+            exit 1
+          fi
+        shell: bash
